### PR TITLE
Fix README Header in Template Folder

### PR DESCRIPTION
**Pull request by SuperC03**

### CODE REVIEW

**Review by prateekbh — APPROVED** [review]

**Comment by rschristian** [comment]
Sorry, but what issue does this fix? Default template uses `{{ name }}` and it works just fine. I don't see any problems.

**Comment by prateekbh** [comment]
my bad i thought this was the README of this repo. should we revert this?

**Comment by rschristian** [comment]
I'd say so, yeah. I don't see any issues with the current behavior. Seems fine?

@SuperC03 is there an actual problem with passing the project name into the ReadMe for you?

**Comment by SuperC03** [comment]
I'm sorry @rschristian @prateekbh I entirely forgot that the {{ name }} was in there for templating. Definitely revert it.

**Pull request merged**
